# Group Channel

## Retrieve Channels [/v1/channels{?filter}]

### GET

+ Request

    + Headers

            Accept: application/vnd.api+json
            Authorization: Bearer <<USERS_JWT_TOKEN>>

+ Response 200

    + Body

            [
              {
                "name": "general",
                "id": "1c6edb3c-92a9-4031-b8b8-f194e2399db6"
              },
              {
                "name": "rick-and-morty",
                "id": "ed42c29b-60cb-4851-a7d3-ec1b3af10788"
              }
            ]

    + Schema

            <!-- include(channel-schema.json) -->

<!-- include(not_found.apib) -->

## Create Channel [/v1/channels]

### POST

+ Request

    + Headers

            Accept: application/vnd.api+json
            Authorization: Bearer <<USERS_JWT_TOKEN>>
            Content-Type: application/vnd.api+json

    + Body

            {
                "data": {
                    "attributes": {
                        "name": "rick-and-morty",
                        "topic": "Shum shum shlippedy dop"
                    }
                }
            }

+ Response 201

            {
              "name": "rick-and-morty",
              "id": "1c6edb3c-92a9-4031-b8b8-f194e2399db6"
            }

    + Schema

            <!-- include(channel-schema.json) -->

+ Response 422

            {
              "errors": [
                {
                  "source": {
                    "pointer": "/data/attributes/topic"
                  },
                  "detail": "is invalid"
                }
              ]
            }

## Update Channel [/v1/channels/{channel_id}]

### PATCH

+ Parameters

    + channel_id (string, required)

+ Request

    + Headers

            Accept: application/vnd.api+json
            Authorization: Bearer <<USERS_JWT_TOKEN>>
            Content-Type: application/vnd.api+json

    + Body

            {
                "data": {
                    "attributes": {
                        "topic": "Wubba lubba dub-dub!"
                    }
                }
            }

+ Response 200

            {
              "name": "rick-and-morty",
              "id": "ed42c29b-60cb-4851-a7d3-ec1b3af10788"
            }

    + Schema

            <!-- include(channel-schema.json) -->

<!-- include(not_found.apib) -->

+ Response 422

            {
              "errors": [
                {
                  "source": {
                    "pointer": "/data/attributes/topic"
                  },
                  "detail": "is invalid"
                }
              ]
            }

## Retrieve Channel [/v1/channels/{channel_id}{?included}]

### GET

+ Parameters

    + channel_id (string, required)

+ Request

    + Headers

            Accept: application/vnd.api+json
            Authorization: Bearer <<USERS_JWT_TOKEN>>

+ Response 200

            {
              "name": "rick-and-morty",
              "id": "ed42c29b-60cb-4851-a7d3-ec1b3af10788"
            }

    + Schema

            <!-- include(channel-schema.json) -->

<!-- include(not_found.apib) -->
