# Data Structures

## Message (object)

+ text (string) - content of the message
+ meta (object) - data related to the message (likes, preview links, etc.)

## Channel (object)

+ name (string) - name given
+ topic (string) - describes the topic of discussion

## User (object)

+ display_name (string) - app display name
+ name (string) - name provided
