# Group Messages

## Retreive Messages [/channels/{channel_id}/messages{?filter}]

::: warning
#### <i class="fa fa-warning"></i> Caution
LOLOL
:::

### GET

+ Parameters

    + channel_id (string, required)

+ Request

    + Headers

            Accept: application/vnd.api+json
            Authorization: Bearer <<USERS_JWT_TOKEN>>

+ Response 200

            [
              {
                "user": {
                  "picture": "https://avatars.githubusercontent.com/u/194892?v=3",
                  "online": false,
                  "nickname": "jamesdphillips",
                  "name": "James Phillips",
                  "last_event_at": null,
                  "id": "github|194892"
                },
                "text": "wubalubadubdub",
                "meta": null,
                "id": "431db0df-a4c2-439e-a283-bb8f63dcbd51",
                "channel": {
                  "name": "ricky-gervais",
                  "id": "1c6edb3c-92a9-4031-b8b8-f194e2399db6"
                }
              }
            ]

    + Schema

            <!-- include(message-schema.json) -->

<!-- include(not_found.apib) -->

## Create Message [/channels/{channel_id}/messages]

### POST

+ Parameters

    + channel_id (string, required)

+ Request

    + Headers

            Accept: application/vnd.api+json
            Authorization: Bearer <<USERS_JWT_TOKEN>>
            Content-Type: application/vnd.api+json

    + Body

            {
                "data": {
                    "attributes": {
                        "text": "wubalubadubdub!"
                    }
                }
            }

+ Response 200

            {
              "user": {
                "picture": "https://avatars.githubusercontent.com/u/194892?v=3",
                "online": false,
                "nickname": "jamesdphillips",
                "name": "James Phillips",
                "last_event_at": null,
                "id": "github|194892"
              },
              "text": "wubalubadubdub",
              "meta": null,
              "id": "431db0df-a4c2-439e-a283-bb8f63dcbd51",
              "channel": {
                "name": "ricky-gervais",
                "id": "1c6edb3c-92a9-4031-b8b8-f194e2399db6"
              }
            }

    + Schema

            <!-- include(message-schema.json) -->

<!-- include(not_found.apib) -->

+ Response 422

            {
              "errors": [
                {
                  "source": {
                    "pointer": "/data/attributes/text"
                  },
                  "detail": "is invalid"
                }
              ]
            }

## Update Message [/messages/{message_id}]

### PATCH

+ Parameters

    + message_id (string, required)

+ Request

    + Headers

            Accept: application/vnd.api+json
            Authorization: Bearer <<USERS_JWT_TOKEN>>
            Content-Type: application/vnd.api+json

    + Body

            {
                "data": {
                    "attributes": {
                        "text": "Shum shum shlippedy dop"
                    }
                }
            }

+ Response 200

            {
              "user": {
                "picture": "https://avatars.githubusercontent.com/u/194892?v=3",
                "online": false,
                "nickname": "jamesdphillips",
                "name": "James Phillips",
                "last_event_at": null,
                "id": "github|194892"
              },
              "text": "wubalubadubdub",
              "meta": null,
              "id": "431db0df-a4c2-439e-a283-bb8f63dcbd51",
              "channel": {
                "name": "ricky-gervais",
                "id": "1c6edb3c-92a9-4031-b8b8-f194e2399db6"
              }
            }

    + Schema

            <!-- include(message-schema.json) -->

<!-- include(not_found.apib) -->

## Retreive Message [/messages/{message_id}{?included}]

### GET

+ Parameters

    + message_id (string, required)

+ Request

    + Headers

            Accept: application/vnd.api+json
            Authorization: Bearer <<USERS_JWT_TOKEN>>

+ Response 200

            {
              "user": {
                "picture": "https://avatars.githubusercontent.com/u/194892?v=3",
                "online": false,
                "nickname": "jamesdphillips",
                "name": "James Phillips",
                "last_event_at": null,
                "id": "github|194892"
              },
              "text": "wubalubadubdub",
              "meta": null,
              "id": "431db0df-a4c2-439e-a283-bb8f63dcbd51",
              "channel": {
                "name": "ricky-gervais",
                "id": "1c6edb3c-92a9-4031-b8b8-f194e2399db6"
              }
            }

    + Schema

            <!-- include(message-schema.json) -->

<!-- include(not_found.apib) -->
