# Group Users

## Retrieve User [/users/{user_id}]

### GET

+ Parameters

    + user_id: `github|194892` (string, required)

+ Request

    + Headers

            Accept: application/vnd.api+json
            Authorization: Bearer <<USERS_JWT_TOKEN>>

+ Response 200

            {
              "jsonapi": {
                "version": "1.0"
              },
              "data": {
                "type": "user",
                "id": "github|194892",
                "attributes": {
                  "picture": "https://avatars.githubusercontent.com/u/194892?v=3",
                  "online": false,
                  "nickname": "jamesdphillips",
                  "name": "James Phillips",
                  "lastEventAt": null
                }
              }
            }

    + Schema

            <!-- include(user-schema.json) -->

<!-- include(not_found.apib) -->
